#!/usr/bin/env bash
set -euo pipefail

DEPLOY_ROOT=${SAM_CONTINUOUS_DEPLOY_ROOT:-/home/ubuntu/sam-audio-deploy}
PIPELINE_ROOT="$DEPLOY_ROOT/pipeline"
PIPELINE_PYTHON="$PIPELINE_ROOT/.venv/bin/python"
WORKSPACE=${SAM_CONTINUOUS_WORKSPACE:-/home/ubuntu/cinematic-continuous-30s}
SOURCE_CACHE=${SAM_CONTINUOUS_SOURCE_CACHE:-$WORKSPACE/source-work}
STAGING_DIR=${SAM_CONTINUOUS_SOURCE_STAGING_DIR:-}
WORKERS=${SAM_CONTINUOUS_SOURCE_DOWNLOAD_WORKERS:-16}
HIGH_WATER=${SAM_CONTINUOUS_DOWNLOADED_HIGH_WATER:-64}
HIGH_WATER_BYTES=${SAM_CONTINUOUS_DOWNLOADED_HIGH_WATER_BYTES:-8589934592}
MINIMUM_FREE_BYTES=${SAM_CONTINUOUS_DOWNLOAD_MINIMUM_FREE_BYTES:-0}
INDEPENDENT=${SAM_CONTINUOUS_SOURCE_DOWNLOAD_INDEPENDENT:-false}
CIRCUIT_FAILURE_THRESHOLD=${SAM_CONTINUOUS_PROVIDER_CIRCUIT_FAILURE_THRESHOLD:-5}
CIRCUIT_COOLDOWN_SECONDS=${SAM_CONTINUOUS_PROVIDER_CIRCUIT_COOLDOWN_SECONDS:-300}
CIRCUIT_MAX_COOLDOWN_SECONDS=${SAM_CONTINUOUS_PROVIDER_CIRCUIT_MAX_COOLDOWN_SECONDS:-3600}
PROVIDER_WEIGHTS=${SAM_CONTINUOUS_SOURCE_PROVIDER_WEIGHTS:-}
YOUTUBE_PROXY_CONFIG=${SAM_YOUTUBE_PROXY_CONFIG:-}

PROXY_ARGS=()
if [[ -n "$YOUTUBE_PROXY_CONFIG" ]]; then
  PROXY_ARGS+=(--youtube-proxy-config "$YOUTUBE_PROXY_CONFIG")
fi

WEIGHT_ARGS=()
if [[ -n "$PROVIDER_WEIGHTS" ]]; then
  WEIGHT_ARGS+=(--provider-weights "$PROVIDER_WEIGHTS")
fi

STAGING_ARGS=()
if [[ -n "$STAGING_DIR" ]]; then
  STAGING_ARGS+=(--staging-dir "$STAGING_DIR")
fi

CONTROL_ARGS=()
if [[ "$INDEPENDENT" != "true" ]]; then
  CONTROL_ARGS+=(--control-file "$WORKSPACE/source-stage-control.json")
fi

export PYTHONPATH="$PIPELINE_ROOT/src"
mkdir -p "$SOURCE_CACHE"
cd "$PIPELINE_ROOT"

exec "$PIPELINE_PYTHON" -m sam_audio_pipeline.source_pipeline download \
  --workspace "$WORKSPACE" \
  --source-cache "$SOURCE_CACHE" \
  "${STAGING_ARGS[@]}" \
  --workers "$WORKERS" \
  --downloaded-high-water "$HIGH_WATER" \
  --downloaded-high-water-bytes "$HIGH_WATER_BYTES" \
  --minimum-free-bytes "$MINIMUM_FREE_BYTES" \
  --circuit-failure-threshold "$CIRCUIT_FAILURE_THRESHOLD" \
  --circuit-cooldown-seconds "$CIRCUIT_COOLDOWN_SECONDS" \
  --circuit-max-cooldown-seconds "$CIRCUIT_MAX_COOLDOWN_SECONDS" \
  "${WEIGHT_ARGS[@]}" \
  --clip-seconds 30 \
  "${CONTROL_ARGS[@]}" \
  --yt-dlp-python "$PIPELINE_PYTHON" \
  "${PROXY_ARGS[@]}"
